# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: projectName
  value: pipe0713 

steps:
- script: |
    echo ${{ variables.projectName }}

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(9f241d6e-16e2-4b2b-a485-cc546f04799b)'
    subscriptionId: '9f241d6e-16e2-4b2b-a485-cc546f04799b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-wus2-dev-expert'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'samplelinkedtemplate/azuredeploy.json'
    overrideParameters: '-projectName ${{ variables.projectName }} -linkedTemplateUri https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/get-started-deployment/linked-template/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate-0710a'